### ISSUE TITLE
mp3 not working 

### ISSUE THREAD

**Issue by ghost** [MarkHjorth/nedry#1]
I'm not sure if it's just me but the mp3 file doesn't appear to be working.

**Comment by MarkHjorth** [comment]
Hi @KyleBrown90 

You're right. At the moment the mp3 file doesn't auto-play.
Most modern browsers block auto-playing audio/video.

I don't think I can fix this. But I'll have to look into it. An unmute button might be a possibility?

**Comment by MarkHjorth** [comment]
Hi @KyleBrown90 

This issue should be fixed now. Let me know what you think.

**Comment by raulssorban** [comment]
> I'm not sure if it's just me but the mp3 file doesn't appear to be working.

You're not working, lmao
